<html>
<head>
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/main.css">
<title>Financial report</title>
</head>
<body>

<h1>Financial report</h1>
${name}
<!--Web Application Context Path = ${pageContext.request.contextPath}-->
<h4>
Report generated by Money Manager for one specified month.
</h4>

<!--MonthData data = MonthHandler.retrieveForMonth(db, year, month);
writeMonthData(writer, year, month, data);

writeHelp(writer);-->

</body>
<h2>Application by <b>Monika Gruszka &amp; Michał Szymański</b></h2>
<h2>Theme created with love by <a href=\"http://pablogarciafernandez.com\" target=\"_blank\">Pablo García Fernández</a></h2>
</html>