package monikamichael.money_manager.engine;

import java.io.PrintWriter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

public class ReportGenerator {
    private static void writeMonthData(final PrintWriter writer,
                                       final int year, final int month, final MonthData data) {
        writer.println("<h3 class=\"month-header\">" + Month.fromInt(month) + " " + year + "</h3>");
        writer.println("<p><table class=\"container\">");

        writeTableHeader(writer, new String[]{"account", " beginning", "end", "balance"});
        writeTableRow(writer, new String[] {
                "main",
                Currency.toString(data.accountBegin),
                Currency.toString(data.accountEnd),
                Currency.toString(data.accountEnd - data.accountBegin)
        });

        writeTableRow(writer, new String[] {
                "wallet",
                Currency.toString(data.walletBegin),
                Currency.toString(data.walletEnd),
                Currency.toString(data.walletEnd - data.walletBegin)
        });

        writeTableRow(writer, new String[] {
                "PayPal",
                Currency.toString(data.payPalBegin),
                Currency.toString(data.payPalEnd),
                Currency.toString(data.payPalEnd - data.payPalBegin)
        });

        writeTableRow(writer, new String[] {
                "TOTAL",
                Currency.toString(data.totalBegin()),
                Currency.toString(data.totalEnd()),
                Currency.toString(data.totalEnd() - data.totalBegin())
        });

        writer.println("</table></p>");

        writer.println("<p><table class=\"container\">");

        writeTableRow(writer, new String[] {
                "<b>After previous month</b>", Currency.toString(data.afterPreviousMonth)
        });
        writeTableRow(writer, new String[] {
                "<b>Salary</b>", Currency.toString(data.salary)
        });
        writeTableRow(writer, new String[] {
                "<b>Food expenses</b>", Currency.toString(data.foodExpenses())
        });
        writeTableRow(writer, new String[] {
                "<b>Balance</b>", Currency.toString(data.balance())
        });


        writeExpandingList(writer, month, data.ownExpenses, "Own Expenses");
        writeExpandingList(writer, month, data.periodicExpenses, "Periodic Expenses");
        writeExpandingList(writer, month, data.otherExpenses, "Other Expenses");
        writeExpandingList(writer, month, data.outOfBudgetExpenses, "Out-of-budget expense");
        writeExpandingList(writer, month, data.debts, "Debts");
        writeExpandingList(writer, month, data.transfersFromSavings, "Transfers from savings");

        writer.println("</table></p>");
        
        writer.println("<p><table class=\"container\">");
        writeTableHeader(writer, new String[]{"", "Clothes", "Cosmetics",
                "Hobby and books", "Dates and meetings", "Other"});
        writeTableRow(writer, new String[] {
                "TOTAL",
                Currency.toString(MonthData.balanceCategory(data.getAllEntries(), "Clothes")),
                Currency.toString(MonthData.balanceCategory(data.getAllEntries(), "Cosmetics")),
                Currency.toString(MonthData.balanceCategory(data.getAllEntries(), "Hobby and books")),
                Currency.toString(MonthData.balanceCategory(data.getAllEntries(), "Dates and meetings")),
                Currency.toString(MonthData.balanceCategory(data.getAllEntries(), "Other")),

        });
        writer.println("</table></p>");
    }

    public static void forOneMonth(final Database db, final PrintWriter writer,
                                   final int month, final int year) {
        writer.println("<html>");
        writer.println("  <head>");
        writer.println("    <title>Financial report</title>");
        writer.println("    <link rel=\"stylesheet\" type=\"text/css\" href=\"src/main/resources/main.css\">");
        writer.println("  </head>");
        writer.println("  <body>");

        writer.println("    <h1>Financial report</h1>");
        writer.println("    <h4>");
        writer.println("      Report generated by Money Manager for one specified month.");
        writer.println("    </h4>");

        MonthData data = MonthHandler.retrieveForMonth(db, year, month);
        writeMonthData(writer, year, month, data);

        writeHelp(writer);

        writer.println("  </body>");
        writer.println("<h2>Application by <b>Monika Gruszka &amp; Michał Szymański</b></h2>");
        writer.println("<h2>Theme created with love by <a href=\"http://pablogarciafernandez.com\" target=\"_blank\">Pablo García Fernández</a></h2>");
        writer.println("</html>");
    }

    public static void forAllMonths(final Database db, final PrintWriter writer) {
        writer.println("<html>");
        writer.println("  <head>");
        writer.println("    <title>Financial report</title>");
        writer.println("    <link rel=\"stylesheet\" type=\"text/css\" href=\"src/main/resources/main.css\">");
        writer.println("  </head>");
        writer.println("  <body>");

        writer.println("    <h1>Financial report</h1>");
        writer.println("    <h4>");
        writer.println("      Report generated by Money Manager for every month");
        writer.println("      included in the database.");
        writer.println("    </h4>");
        db.executeSqlQuery("SELECT YEAR, MONTH FROM MONTHS ORDER BY YEAR DESC, MONTH DESC", new SqlQueryClient() {
            @Override
            public void onStatementReady(PreparedStatement statement) throws SQLException {
            }

            @Override
            public void onResult(ResultSet resultSet) throws SQLException {
                boolean first = true;
                while (resultSet.next()) {
                    int year = resultSet.getInt("YEAR");
                    int month = resultSet.getInt("MONTH");

                    if (first) {
                        // Also print information about the next month (first not included in the database)
                        int nextMonthYear = year;
                        int nextMonthMonth = month + 1;
                        if (nextMonthMonth > 12) {
                            nextMonthMonth = 1;
                            ++nextMonthYear;
                        }
                        MonthData data = MonthHandler.retrieveForMonth(db, nextMonthYear, nextMonthMonth);
                        writeMonthData(writer, nextMonthYear, nextMonthMonth, data);

                        first = false;
                    }

                    MonthData data = MonthHandler.retrieveForMonth(db, year, month);
                    writeMonthData(writer, year, month, data);
                }
            }
        });

        writeHelp(writer);

        writer.println("  </body>");
        writer.println("<h2>Application by <b>Monika Gruszka &amp; Michał Szymański</b></h2>");
        writer.println("<h2>Theme created with love by <a href=\"http://pablogarciafernandez.com\" target=\"_blank\">Pablo García Fernández</a></h2>");
        writer.println("</html>");
    }

    private static void writeTableHeader(PrintWriter writer, String[] heading) {
        writer.println("<thead>");
        writer.println("  <tr>");
        for (String column : heading) {
            writer.println("<th>" + column + "</th>");
        }
        writer.println("  </tr>");
        writer.println("<thead>");
    }

    private static void writeTableRow(PrintWriter writer, String[] cells) {
        writer.println("  <tr>");
        for (String cell : cells) {
            writer.println("<td>" + cell + "</td>");
        }
        writer.println("  </tr>");
    }

    private static  void writeExpandingList(PrintWriter writer, int month, List<Entry> data, String uniqueId) {
        writer.println("<tr><p><td>" +
                "<input class=\"toggle\" id=\"toggle" + uniqueId + Month.fromInt(month)  +  "\" type=\"checkbox\">" +
                "<label for=\"toggle" + uniqueId + Month.fromInt(month) + "\"><b>"+uniqueId +"</b></label>" +
                "<div class=\"expand\">" +
                "    <section>" +
                "<p><table class=\"container\">");
        for (Entry entry : data) {
            writer.println("<tr>" +
                    "<td>" + entry.description + "</td>" +
                    "<td>" + Currency.toString(entry.value) + "</td>" +
                    "<td>" + entry.category + "</td>" +
                    "</tr>");
        }
        writer.println("</table></p> </section></div></td><td>");
        writer.println(Currency.toString(MonthData.balanceEntries(data)));
        writer.println("</td></tr></p>");
    }

    private static void writeHelp(PrintWriter writer) {
        writer.println("<div id=\"help\">");
        writer.println("<h4>Help</h4>" +
                "<img src=\"accounts.png\" style=\"width: 14cm; display: block; margin: 0 auto;\"/>" +
                "<p>Every month, you enter <b>salary</b> you earned that month and amount that " +
                "you wish to be your <b>in-budget income</b>. The rest of your salary is " +
                "<i>out-of-budget</i> income (don't enter it in out-of-budget events yourself).</p>" +
                "<p>You can also have other out-of-budget events, labeled <i>gifts</i> " +
                "and <i>out-of-budget expenses</i>. Put them into <b>out-of-budget events</b> " +
                "table. Gifts go with a positive sign into that table and expenses with negative sign.</p>" +
                "<p>If you transferred some money from savings account into the main account, " +
                "report it in <b>transfers from savings</b>. But also return the money " +
                "as soon as possible, trying to keep transfers zero. Report returned money " +
                "in the same table with negative sign.</p>" +
                "<p>If you lend some money, enter it in <b>money lent</b> table. " +
                "The rules for signs are as follows:" +
                "<ul>" +
                "<li>+ when you lend money to someone</li>" +
                "<li>- when that someone gives the money back</li>" +
                "<li>- when you borrow money from someone</li>" +
                "<li>+ when you give the money back to them</li>" +
                "</ul></p>" +
                "<p><b>In-budget expense</b> can be reported in either of the following categories:" +
                "<ol>" +
                "  <li>own expenses</li>" +
                "  <li>periodic expenses</li>" +
                "  <li>other expenses</li>" +
                "</ol>" +
                "You are free to choose whichever category, but periodic expenses have an additional feature: " +
                "they can be copied from the previous month when entering a new month data." +
                "</p>" +
                "<p>You don't enter <i>food expenses</i> manually. Instead, it is calculated automatically " +
                "based on Main Account balance and the rest of the data entered.</p>");
        writer.println("</div>");
    }
}
